[project]
name = "pj"
version = "0.1.0"
description = "pj is a CLI tool."
requires-python = ">=3.11,<4"
dependencies = [
    "rich>=14.1.0,< 14.2.0",
]
readme = "README.md"
authors = [{ name = "Mahadi Xion", email = "mhxions@gmail.com" }]
maintainers = [{ name = "Mahadi Xion", email = "mhxions@gmail.com" }]
license = "AGPL-3.0-only"
keywords = [
    "cli",
    "ai",
]
[project.scripts]
pj = "pj.pj:prettify"

[build-system]
requires = ["uv_build>=0.7.19,<0.8.0"]
build-backend = "uv_build"
